<a href="https://colab.research.google.com/github/varmaaggadi/demo/blob/main/interview.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
l1=[1,2,3,4]
l1

[1, 2, 3, 4]

In [2]:
import numpy as np
l=np.array([1,2,3,4])
l

array([1, 2, 3, 4])

In [3]:
l*2

array([2, 4, 6, 8])

In [6]:
np.multiply(l1,2)


array([2, 4, 6, 8])

In [8]:
import sys
sys.getsizeof(l1)

104

In [10]:
l.itemsize

8

In [30]:
n=1
k=[]
for i in range(n):
  l=list(map(int,input().split()))
  if l[i]>l[i+1]:
    t=l[i]
    l[i]=l[i+1]
    l[i+1]=t
    i=i+1
  
 
print(l)

      


2 1 3
[1, 2, 3]


In [31]:
import pandas as pd
data={'apples':[4,1,2],'banana':[6,2,3]}
df=pd.DataFrame(data)
df

apples  banana
0       4       6
1       1       2
2       2       3

In [32]:
# adding customer names to data
df=pd.DataFrame(data,index=['varma','venky','billa'])
df

apples  banana
varma       4       6
venky       1       2
billa       2       3

In [35]:
#number of purchases by customer
numorder=df.loc['varma']
numorder

apples    4
banana    6
Name: varma, dtype: int64